import { readdir, mkdir } from "node:fs/promises";
import { join, basename, relative } from "node:path";
import packageJson from "../package.json";

const SRC_DIR = "src";
const WWW_DIR = "www";
const INJECTED_DIR = join(SRC_DIR, "injected");
const APP_DIR = join(SRC_DIR, "app");

async function getFiles(dir: string, extension: string): Promise<string[]> {
  try {
    const files = await readdir(dir);
    return files.filter((file) => file.endsWith(extension));
  } catch (e) {
    return [];
  }
}

async function build() {
  console.log("🏗️  Starting build process...");

  // 1. Discover Assets
  const cssRules = await getFiles(join(INJECTED_DIR, "css", "rules"), ".css");
  const htmlTemplates = await getFiles(join(INJECTED_DIR, "html"), ".html");
  const injectedScripts = await getFiles(join(INJECTED_DIR, "ts"), ".ts");
  const dataFiles = await getFiles(join(INJECTED_DIR, "data"), ".json");

  console.log(`Found ${cssRules.length} CSS rules`);
  console.log(`Found ${htmlTemplates.length} HTML templates`);
  console.log(`Found ${injectedScripts.length} Injected scripts`);
  console.log(`Found ${dataFiles.length} Data files`);

  // 2. Generate Manifest
  const manifestContent = `
// This file is auto-generated by scripts/build.ts
// Do not edit this file directly.

export const AssetManifest = {
  cssRules: ${JSON.stringify(cssRules)},
  htmlTemplates: ${JSON.stringify(htmlTemplates)},
  injectedScripts: ${JSON.stringify(injectedScripts.map(f => f.replace('.ts', '.js')))},
  dataFiles: ${JSON.stringify(dataFiles)},
};
`;

  await mkdir(join(APP_DIR, "generated"), { recursive: true });
  await Bun.write(join(APP_DIR, "generated", "AssetManifest.ts"), manifestContent);
  console.log("✅ Generated AssetManifest.ts");

  const version = packageJson.version;
  await Bun.write(join(APP_DIR, "generated", "Version.ts"), `export const AppVersion = "${version}";`);
  console.log(`✅ Generated Version.ts (${version})`);

  // 3. Clean & Prepare WWW
  await mkdir(join(WWW_DIR, "app", "js"), { recursive: true });
  await mkdir(join(WWW_DIR, "app", "css"), { recursive: true });
  await mkdir(join(WWW_DIR, "injected", "js"), { recursive: true });
  await mkdir(join(WWW_DIR, "injected", "css", "rules"), { recursive: true });
  await mkdir(join(WWW_DIR, "injected", "html"), { recursive: true });
  await mkdir(join(WWW_DIR, "injected", "data"), { recursive: true });

  // 4. Build App
  console.log("📦 Bundling App...");
  await Bun.build({
    entrypoints: [join(APP_DIR, "main.ts")],
    outdir: join(WWW_DIR, "app", "js"),
    sourcemap: "external",
    minify: false, // Keep readable for now, change to true for prod
  });

  // 5. Build Injected Scripts
  console.log("📦 Bundling Injected Scripts...");
  if (injectedScripts.length > 0) {
      await Bun.build({
        entrypoints: injectedScripts.map(f => join(INJECTED_DIR, "ts", f)),
        outdir: join(WWW_DIR, "injected", "js"),
        root: join(INJECTED_DIR, "ts"),
        sourcemap: "external",
        minify: false, 
      });
  }

  // 6. Copy Assets
  console.log("📂 Copying static assets...");
  
  // App HTML/CSS
  await Bun.write(join(WWW_DIR, "index.html"), Bun.file(join(APP_DIR, "index.html")));
  await Bun.write(join(WWW_DIR, "app", "css", "style.css"), Bun.file(join(APP_DIR, "style.css")));

  // Injected HTML
  for (const html of htmlTemplates) {
    await Bun.write(
      join(WWW_DIR, "injected", "html", html),
      Bun.file(join(INJECTED_DIR, "html", html))
    );
  }

  // Injected CSS
  for (const css of cssRules) {
    await Bun.write(
      join(WWW_DIR, "injected", "css", "rules", css),
      Bun.file(join(INJECTED_DIR, "css", "rules", css))
    );
  }

  // Injected Data
  for (const file of dataFiles) {
    await Bun.write(
      join(WWW_DIR, "injected", "data", file),
      Bun.file(join(INJECTED_DIR, "data", file))
    );
  }

  console.log("🎉 Build complete!");
}

build().catch(console.error);
